---
- name: Ensure postfix and SAS libraries are installed.
  apt:
    name: 
      - postfix
      - libsasl2-modules
    update_cache: yes
    state: present

- name: Update Postfix configuration.
  lineinfile:
    dest: "{{ postfix_config_file }}"
    line: "{{ item.name }} = {{ item.value }}"
    regexp: "^{{ item.name }} ="
    mode: 0644
  with_items:
    - name: inet_interfaces
      value: "{{ postfix_inet_interfaces }}"
    - name: inet_protocols
      value: "{{ postfix_inet_protocols }}"
    - name: myhostname
      value: "{{ postfix_hostname }}"
    - name: relayhost 
      value: "{{ postfix_smtp_upstream_server }}"
    - name: smtp_sasl_auth_enable 
      value: 'yes'
    - name: smtp_sasl_security_options 
      value: 'noanonymous'
    - name: smtp_sasl_password_maps 
      value: "hash:{{ postfix_sasl_secret_config }}"
    - name: smtp_tls_security_level 
      value: 'encrypt'
    - name: smtp_tls_CAfile 
      value: '/etc/ssl/certs/ca-certificates.crt'

  notify: restart postfix

- name: Create sasl passwd file
  template:
    src: etc/postfix/sasl/sasl_passwd.j2
    dest: "{{ postfix_sasl_secret_config }}"
    owner: root
    group: root
    mode: 0600

- name: Hash sasl passwd file
  command: "postmap {{ postfix_sasl_secret_config }}"
  args:
    creates: "{{ postfix_sasl_secret_config }}.db"

- name: Ensure postfix is started and enabled at boot.
  service:
    name: postfix
    state: "{{ postfix_service_state }}"
    enabled: "{{ postfix_service_enabled }}"
